export const NAVBARTOGGLED = "NAVBARTOGGLED";

export const GET_MOVIEPICK = "GET_MOVIEPICK";
export const GET_MOVIEPICK_SUCCESS = "GET_MOVIEPICK_SUCCESS";
export const GET_MOVIEPICK_ERROR = "GET_MOVIEPICK_ERROR";

export const GET_MOVIEPICK_TWO = "GET_MOVIEPICK_TWO";
export const GET_MOVIEPICK_SUCCESS_TWO = "GET_MOVIEPICK_SUCCESS_TWO";
export const GET_MOVIEPICK_ERROR_TWO = "GET_MOVIEPICK_ERROR_TWO";

export const GET_MOVIELIST = "GET_MOVIELIST";
export const GET_MOVIELIST_SUCCESS = "GET_MOVIELIST_SUCCESS";
export const GET_MOVIELIST_ERROR = "GET_MOVIELIST_ERROR";
