export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const NAVBARTOGGLED = "NAVBARTOGGLED";

export const GET_MOVIEPICK = "GET_MOVIEPICK";
export const GET_MOVIEPICK_SUCCESS = "GET_MOVIEPICK_SUCCESS";
export const GET_MOVIEPICK_ERROR = "GET_MOVIEPICK_ERROR";

export const GET_MOVIEPICK_TWO = "GET_MOVIEPICK_TWO";
export const GET_MOVIEPICK_SUCCESS_TWO = "GET_MOVIEPICK_SUCCESS_TWO";
export const GET_MOVIEPICK_ERROR_TWO = "GET_MOVIEPICK_ERROR_TWO";
